name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: fortran-lang/setup-fortran@v1
      id: setup-fortran

    - name: Build
      working-directory: ./src
      run: make FORTRAN_COMPILER="gfortran"
